apiVersion: v2
name: cve-processor
description: A Helm chart for deploying PostgreSQL and application job
version: 0.1.0

dependencies:
- name: postgresql
  version: 12.1.5
  repository: https://charts.bitnami.com/bitnami

