global:
  postgresql:
    auth:
      postgresPassword: "changeme"
      username: "cve"
      password: "changeme"
      database: "mydatabase"

job:
  image:
    repository: rahhul1309/db-migration
    tag: "1.0.3"
  env:
    FLYWAY_URL: "jdbc:postgresql://cve-processor-postgresql.default.svc.cluster.local:5432/mydatabase"
    FLYWAY_SCHEMAS: "cve"
    FLYWAY_USER: "cve"
    FLYWAY_PASSWORD: "changeme"
    FLYWAY_LOCATIONS: "filesystem:/usr/src/flyway/sql"
  volumeMounts:
    - mountPath: /flyway/sql
      name: flyway-sql
  volumes:
    - name: flyway-sql
      emptyDir: {}

storageClass:
  name: aws-pg-sc
  isDefaultClass: true
  provisioner: ebs.csi.aws.com
  parameters:
    type: gp2
    kmsKeyId: 