namespace: namespace3
replicas: 3
imagePullSecrets:
  name: docker-hub-secret
initContainers:
  waitForPostgresql:
    image: busybox
    command: ['sh', '-c', 'until nslookup "postgresql-ha-pgpool.namespace3.svc.cluster.local"; do echo waiting for postgres; sleep 2; done']
job:
  namespace: namespace1
  image:
    repository: rahhul1309/db-migration
    tag: 1.0.3
  env:
    FLYWAY_URL: jdbc:postgresql://postgresql-ha-pgpool.namespace3.svc.cluster.local:5432/mydatabase
    FLYWAY_SCHEMAS: public
    FLYWAY_USER: myuser
    FLYWAY_PASSWORD: mypassword
    FLYWAY_LOCATIONS: filesystem:/flyway/sql
  containers:
    webappCveProcessor:
      image: rahhul1309/webapp-cve-processor:1005
      env:
        KAFKA_BROKERS: kafka-broker-0.kafka-broker-headless.namespace2.svc.cluster.local:9092
containers:
  webappCveConsumer:
    image: rahhul1309/webapp-cve-consumer:1008
    env:
      KAFKA_BROKERS: kafka-broker-0.kafka-broker-headless.namespace2.svc.cluster.local:9092,kafka-broker-1.kafka-broker-headless.namespace2.svc.cluster.local:9092,kafka-broker-2.kafka-broker-headless.namespace2.svc.cluster.local:9092
      KAFKA_CLUSTER: kafka.namespace2.svc.cluster.local:9092
secret:
  name: docker-hub-secret
  dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJyYWhodWwxMzA5IiwicGFzc3dvcmQiOiJkY2tyX3BhdF90YXF1RmQ2bUlJRWxWaFBvRVlpQ1Nmd1lNS3MiLCJlbWFpbCI6InJhaGh1bGdhbmVlc2hyZWRkaWFiYmF2YXJhbUBnbWFpbC5jb20iLCJhdXRoIjoiY21Gb2FIVnNNVE13T1Rwa1kydHlYM0JoZEY5MFlYRjFSbVEyYlVsSlJXeFdhRkJ2UlZscFExTm1kMWxOUzNNPSJ9fX0=

storageClass:
  name: aws-pg-sc
  isDefaultClass: true
  provisioner: ebs.csi.aws.com
  parameters:
    type: gp2
    kmsKeyId: 
