image:
  repository: rahhul1309/webapp-cve-processor
  tag: 1.1.0
  pullPolicy: Always

initImage:
  repository: rahhul1309/db-migration
  tag: 200
  pullPolicy: Always

volumeMounts:
  - mountPath: /usr/data
    name: local-data

volumes:
  hostPath: /mnt/c/Users/Owner/Downloads/cves  # Adjusted for correct translation
