flyway:
  url: "jdbc:postgresql://host.docker.internal:5430/cve?sslmode=disable"
  user: "cve"
  password: "changeme"

database:
  url: "postgres://cve:changeme@host.docker.internal:5430/cve?sslmode=disable"

initImage:
  repository: rahhul1309/db-migration
  tag: latest
  pullPolicy: IfNotPresent

image:
  repository: rahhul1309/webapp-cve-processor
  tag: latest
  pullPolicy: IfNotPresent
