apiVersion: example.example.com/v1
kind: GitHubReleasesMonitor
metadata:
  name: cvelist-monitor
  namespace: namespace1
spec:
  url: https://api.github.com/repos/CVEProject/cvelistV5/releases
  monitorFrom: "2024-08-08T20:00:00Z"