apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: job-network-policy
  namespace: namespace1
spec:
  podSelector:
    matchLabels:
      app: cve-job
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
  egress:
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/instance: kafka
          app.kubernetes.io/name: kafka
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: namespace2
  - to:
      - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
  - to:
    - ipBlock:
        cidr: 140.82.112.0/20
    ports:
      - protocol: TCP
        port: 443