apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: consumer-network-policy
  namespace: namespace3
spec:
  podSelector:
    matchLabels:
      app: webapp-cve-consumer
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: kafka
              app.kubernetes.io/name: kafka
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: namespace2
      ports:
        - protocol: TCP
          port: 9092
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: pgpool
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: namespace3
      ports:
        - protocol: TCP
          port: 5432
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: kafka
              app.kubernetes.io/name: kafka
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: namespace2
      ports:
        - protocol: TCP
          port: 9092
    - to:
      - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system