apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-network-policy
  namespace: namespace2
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: kafka
      app.kubernetes.io/name: kafka
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: kafka
              app.kubernetes.io/name: kafka
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: namespace2
    - from:
        - podSelector:
            matchLabels:
              app: cve-job
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: namespace1
      ports:
        - protocol: TCP
          port: 9092
    - from:
        - podSelector:
            matchLabels:
              app: webapp-cve-consumer
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: namespace3
      ports:
        - protocol: TCP
          port: 9092
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: kafka
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: namespace2
    - to:
        - podSelector:
            matchLabels:
              app: webapp-cve-consumer
          namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: namespace3
      ports:
        - protocol: TCP
          port: 9092
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: istio-system
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring