apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kafka-access
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: kafka
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: webapp-cve-consumer
    - podSelector:
        matchLabels:
          app: webapp-cve-processor
    ports:
    - protocol: TCP
      port: 9092
