apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: deployment-consumer-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: 1
  selector:
      matchLabels:
        app: webapp-cve-consumer
