apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  initContainers:
    - name: db-migrations
      image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
      imagePullPolicy: {{ .Values.initImage.pullPolicy }}
      env:
        - name: FLYWAY_URL
          valueFrom:
            secretKeyRef:
              name: cve-database-secret
              key: FLYWAY_URL
        - name: FLYWAY_SCHEMAS
          value: "cve"
        - name: FLYWAY_USER
          valueFrom:
            secretKeyRef:
              name: cve-database-secret
              key: FLYWAY_USER
        - name: FLYWAY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cve-database-secret
              key: FLYWAY_PASSWORD
        - name: FLYWAY_LOCATIONS
          value: "filesystem:/flyway/sql"
      command: ["flyway"]
      args: ["migrate"]
      volumeMounts:
        - mountPath: /flyway/sql
          name: flyway-sql
  containers:
    - name: {{ .Chart.Name }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cve-database-secret
              key: DATABASE_URL
  imagePullSecrets:
    - name: docker-hub-secret
  volumes:
    - name: flyway-sql
      emptyDir: {}
  restartPolicy: Always
