apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  initContainers:
    - name: db-migrations
      image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag }}"
      imagePullPolicy: {{ .Values.initImage.pullPolicy }}
      env:
        - name: FLYWAY_URL
          value: "jdbc:postgresql://host.docker.internal:5430/cve?sslmode=disable"
        - name: FLYWAY_SCHEMAS
          value: "cve"
        - name: FLYWAY_USER
          value: "cve"
        - name: FLYWAY_PASSWORD
          value: "changeme"
        - name: FLYWAY_LOCATIONS
          value: "filesystem:/flyway/sql"
      command: ["flyway"]
      args: ["migrate"]
      volumeMounts:
        - mountPath: /flyway/sql
          name: flyway-sql
  containers:
    - name: {{ .Chart.Name }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      env:
        - name: DATABASE_URL
          value: "postgres://cve:changeme@host.docker.internal:5430/cve?sslmode=disable"
  imagePullSecrets:
    - name: docker-hub-secret
  volumes:
    - name: flyway-sql
      emptyDir: {}
  restartPolicy: Always
