apiVersion: batch/v1
kind: Job
metadata:
  name: webapp-cve-processor-job
  labels:
    app: cve-job
  namespace: {{ .Values.job.namespace }}
spec:
  template:
    metadata:
      labels:
        app: cve-job
    spec:
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
      containers:
        - name: webapp-cve-processor
          image: {{ .Values.job.containers.webappCveProcessor.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BROKERS
              value: {{ .Values.job.containers.webappCveProcessor.env.KAFKA_BROKERS }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1"
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - cve-job
            topologyKey: topology.kubernetes.io/zone
      volumes:
        - name: flyway-sql
          emptyDir: {}
