{{- range .Values.namespaces }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: {{ .name }}
spec:
  hard:
    requests.cpu: {{ $.Values.resourceQuotas.hard.requests.cpu }}
    requests.memory: {{ $.Values.resourceQuotas.hard.requests.memory }}
    limits.cpu: {{ $.Values.resourceQuotas.hard.limits.cpu }}
    limits.memory: {{ $.Values.resourceQuotas.hard.limits.memory }}
{{- end }}
